"""add interaction_events model

Revision ID: 7ce6683915f3
Revises: dacb437618a2
Create Date: 2026-03-09 16:17:48.627074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce6683915f3'
down_revision: Union[str, None] = 'dacb437618a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('learning_object_id', sa.UUID(), nullable=True),
    sa.Column('item_version_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('ANSWER_CHANGE', 'FLAG_TOGGLE', 'NAVIGATION', name='interactioneventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_session_id'), 'interaction_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_events_session_id'), table_name='interaction_events')
    op.drop_table('interaction_events')
    # ### end Alembic commands ###
