"""add provision_time_multiplier to user

Revision ID: dacb437618a2
Revises: 89bdb993a472
Create Date: 2026-03-03 02:55:47.163499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacb437618a2'
down_revision: Union[str, None] = '89bdb993a472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('users', sa.Column('provision_time_multiplier', sa.Float(), nullable=True))
    # Update existing rows to 1.0
    op.execute("UPDATE users SET provision_time_multiplier = 1.0")
    # Make it non-nullable
    op.alter_column('users', 'provision_time_multiplier', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provision_time_multiplier')
    # ### end Alembic commands ###
