"""add grading tables and scoring config

Revision ID: eb86591258e8
Revises: 1c33c55d5f3a
Create Date: 2026-04-06 22:02:45.796933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb86591258e8'
down_revision: Union[str, None] = '1c33c55d5f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('learning_object_id', sa.UUID(), nullable=False),
    sa.Column('item_version_id', sa.UUID(), nullable=False),
    sa.Column('points_awarded', sa.Float(), nullable=False),
    sa.Column('points_possible', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('graded_by', sa.UUID(), nullable=True),
    sa.Column('is_auto_graded', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('rubric_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('student_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_grades_session_id'), 'question_grades', ['session_id'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('test_definition_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grading_status', sa.Enum('UNGRADED', 'AUTO_GRADED', 'PARTIALLY_GRADED', 'FULLY_GRADED', name='gradingstatus'), nullable=False),
    sa.Column('questions_graded', sa.Integer(), nullable=False),
    sa.Column('questions_total', sa.Integer(), nullable=False),
    sa.Column('letter_grade', sa.String(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_definition_id'], ['test_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_results_session_id'), 'session_results', ['session_id'], unique=True)
    op.create_index(op.f('ix_session_results_student_id'), 'session_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_session_results_test_definition_id'), 'session_results', ['test_definition_id'], unique=False)
    op.add_column('test_definitions', sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_definitions', 'scoring_config')
    op.drop_index(op.f('ix_session_results_test_definition_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_student_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_session_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_question_grades_session_id'), table_name='question_grades')
    op.drop_table('question_grades')
    # ### end Alembic commands ###
